# -*- coding: utf-8 -*-
"""Streamlit-app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJY8aYHKUqDt1Hw8ZFkR-orMYJQCVR-g
"""

import streamlit as st
import numpy as np
import pandas as pd
import joblib
from tensorflow.keras.models import load_model

# Load models
@st.cache_resource
def load_all():
    scaler = joblib.load('scaler.pkl')
    kmeans = joblib.load('kmeans.pkl')
    encoder = load_model('encoder.keras')
    data = pd.read_csv('rfm_data.csv')
    return scaler, kmeans, encoder, data

scaler, kmeans, encoder, data = load_all()

st.title("Customer Segmentation System")

# Input
st.header("Enter Customer Data")
recency = st.number_input("Recency", min_value=0)
frequency = st.number_input("Frequency", min_value=0)
monetary = st.number_input("Monetary", min_value=0.0)

# Prediction
if st.button("Predict Segment"):
    input_data = np.array([[recency, frequency, monetary]])
    scaled = scaler.transform(input_data)
    encoded = encoder.predict(scaled)
    cluster = kmeans.predict(encoded)[0]

    st.success(f"Cluster: {cluster}")

# Dataset
if st.checkbox("Show Dataset"):
    st.dataframe(data.head())

# Cluster insights
if st.checkbox("Cluster Insights"):
    st.write(data.groupby('Cluster').mean())

# Similar customers
if st.checkbox("Find Similar Customers"):
    cust_id = st.number_input("Customer ID")

    if st.button("Find Similar"):
        from sklearn.metrics.pairwise import cosine_similarity

        features = data[['Recency','Frequency','Monetary']]
        sim = cosine_similarity(features)

        idx = data[data['CustomerID'] == cust_id].index

        if len(idx) == 0:
            st.error("Customer not found")
        else:
            idx = idx[0]
            scores = sim[idx]
            top_idx = scores.argsort()[::-1][1:6]

            st.write(data.iloc[top_idx])